// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabMessage } from "./TabMessage";

/**
 * Everything an outside process may say to mercury. A sender cannot say anything else, so remote
 * key injection and remote quit are unrepresentable rather than filtered.
 *
 * `MercuryEvent` deliberately does not derive `Deserialize`: deriving it would make
 * `MercuryEvent::Key` and `MercuryEvent::Quit` constructible from the wire, and "no remote
 * keyboard, no remote kill" would be a rule some match arm enforces rather than something the
 * types say.
 *
 */
export type IncomingEvent = { "kind": "IncomingEvent.Tab", "value": TabMessage };
