//! End-to-end exercise of the runtime against hand-written impls, in the shape
//! `#[derive(Rayban)]` will generate. This test lives in a separate crate from
//! `rayban`, so it also proves the design is orphan-rule safe: a multi-parent
//! node's path is a local enum, so its `From` impls are legal here.
//!
//! Tree: `MediaType -> {Album, Song} -> Title (two parents) -> Credit (leaf)`.

use rayban::{Path, Resolve};

enum MediaType {
    Album(Album),
    Song(Song),
}
struct Album {
    title: Title,
}
struct Song {
    title: Title,
}
struct Title {
    credit: Credit,
}
struct Credit {
    name: String,
}

// Single-parent paths are a plain `Path` alias.
type AlbumPath<'a> = Path<Album, &'a mut MediaType>;
type SongPath<'a> = Path<Song, &'a mut MediaType>;

// Title has two parents, so its path is a local enum, one variant per parent.
enum TitlePath<'a> {
    Album(Path<Title, AlbumPath<'a>>),
    Song(Path<Title, SongPath<'a>>),
}
// What `into_parent` returns: the parent path it came from.
enum TitleParent<'a> {
    Album(AlbumPath<'a>),
    Song(SongPath<'a>),
}

// Credit has one parent, so its path is a plain `Path` alias over Title's path.
type CreditPath<'a> = Path<Credit, TitlePath<'a>>;

enum MediaResolved<'a> {
    Credit(CreditPath<'a>),
}

// Generated by the route enum's derive: trivial wraps (local target, so legal),
// plus the dispatching accessors.
impl<'a> From<Path<Title, AlbumPath<'a>>> for TitlePath<'a> {
    fn from(p: Path<Title, AlbumPath<'a>>) -> Self {
        Self::Album(p)
    }
}
impl<'a> From<Path<Title, SongPath<'a>>> for TitlePath<'a> {
    fn from(p: Path<Title, SongPath<'a>>) -> Self {
        Self::Song(p)
    }
}
impl<'a> TitlePath<'a> {
    fn get_mut(&mut self) -> &mut Title {
        match self {
            Self::Album(p) => p.get_mut(),
            Self::Song(p) => p.get_mut(),
        }
    }
    fn into_parent(self) -> TitleParent<'a> {
        match self {
            Self::Album(p) => TitleParent::Album(p.into_parent()),
            Self::Song(p) => TitleParent::Song(p.into_parent()),
        }
    }
}

// Resolve impls. Every descent is `from_fn(parent_path, edge).into()`: the edge
// box is the parent's own field (or variant), and `.into()` is identity for a
// single-parent child and the wrap above for a multi-parent child.
impl Resolve for MediaType {
    type Path<'a> = &'a mut Self;
    type Resolved<'a> = MediaResolved<'a>;
    fn resolve<'a>(media: &'a mut Self) -> MediaResolved<'a>
    where
        Self: 'a,
    {
        match media {
            Self::Album(_) => <Album as Resolve>::resolve(Path::from_fn(media, |o| {
                let Self::Album(a) = &mut **o else {
                    unreachable!()
                };
                a
            })),
            Self::Song(_) => <Song as Resolve>::resolve(Path::from_fn(media, |o| {
                let Self::Song(s) = &mut **o else {
                    unreachable!()
                };
                s
            })),
        }
    }
}
impl Resolve for Album {
    type Path<'a> = AlbumPath<'a>;
    type Resolved<'a> = MediaResolved<'a>;
    fn resolve<'a>(p: AlbumPath<'a>) -> MediaResolved<'a>
    where
        Self: 'a,
    {
        <Title as Resolve>::resolve(Path::from_fn(p, |ap| &mut ap.get_mut().title).into())
    }
}
impl Resolve for Song {
    type Path<'a> = SongPath<'a>;
    type Resolved<'a> = MediaResolved<'a>;
    fn resolve<'a>(p: SongPath<'a>) -> MediaResolved<'a>
    where
        Self: 'a,
    {
        <Title as Resolve>::resolve(Path::from_fn(p, |sp| &mut sp.get_mut().title).into())
    }
}
impl Resolve for Title {
    type Path<'a> = TitlePath<'a>;
    type Resolved<'a> = MediaResolved<'a>;
    fn resolve<'a>(p: TitlePath<'a>) -> MediaResolved<'a>
    where
        Self: 'a,
    {
        <Credit as Resolve>::resolve(Path::from_fn(p, |tp| &mut tp.get_mut().credit))
    }
}
impl Resolve for Credit {
    type Path<'a> = CreditPath<'a>;
    type Resolved<'a> = MediaResolved<'a>;
    fn resolve<'a>(p: CreditPath<'a>) -> MediaResolved<'a>
    where
        Self: 'a,
    {
        MediaResolved::Credit(p)
    }
}

fn album(name: &str) -> MediaType {
    MediaType::Album(Album {
        title: Title {
            credit: Credit {
                name: name.to_owned(),
            },
        },
    })
}

fn song(name: &str) -> MediaType {
    MediaType::Song(Song {
        title: Title {
            credit: Credit {
                name: name.to_owned(),
            },
        },
    })
}

#[test]
fn resolves_through_album_mutates_leaf_and_ancestor() {
    let mut media = album("Roger");
    match <MediaType as Resolve>::resolve(&mut media) {
        MediaResolved::Credit(mut cp) => {
            cp.get_mut().name.push_str(" Taylor"); // mutate the leaf
            let title = cp.into_parent(); // up: Credit -> Title's path
            match title.into_parent() {
                // up again: Title -> which parent
                TitleParent::Album(mut ap) => ap.get_mut().title.credit.name.push('!'),
                TitleParent::Song(_) => unreachable!("resolved through an album"),
            }
        }
    }
    let MediaType::Album(a) = &media else {
        unreachable!()
    };
    assert_eq!(a.title.credit.name, "Roger Taylor!");
}

#[test]
fn resolves_through_song_picks_the_song_parent() {
    let mut media = song("Freddie");
    match <MediaType as Resolve>::resolve(&mut media) {
        MediaResolved::Credit(cp) => match cp.into_parent().into_parent() {
            TitleParent::Song(mut sp) => assert_eq!(sp.get_mut().title.credit.name, "Freddie"),
            TitleParent::Album(_) => unreachable!("resolved through a song"),
        },
    }
}

#[test]
fn parent_reads_shared_without_consuming() {
    let mut media = album("Brian");
    match <MediaType as Resolve>::resolve(&mut media) {
        MediaResolved::Credit(cp) => {
            // Shared read one level up (Credit's path -> Title's path) without consuming.
            match cp.parent() {
                TitlePath::Album(_) => {}
                TitlePath::Song(_) => unreachable!("resolved through an album"),
            }
            let _ = cp.into_parent();
        }
    }
}
